server:
  port: 8081

spring:
  application:
    name: catalog-write

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update